general:
  backups_path: "/home/admins/backup/"
  ibcmd_path: "/opt/1cv8/x86_64/8.5.1.1529/"  #Обязательно после каждого обновления исправлять на новый!
  log_path: "/home/admins/backup/"
  1c_stop: true                               #Останавливать службу сервера 1С на время выполнения функций программы. (рекомендуется, но не обязательно)
  time_to_start: "23:00"                      #Время для запуска утилиты
  secrets_file: "/home/admins//go-projects/maintenance_1C/secrets.yaml"
  mount_path: "/mnt/"                         #Каталог для временного монтирования сетевых файловых баз при работе из Linux  

server_settings:
  dbms: "PostgreSQL"                          #Может быть только PostgreSQL или MSSQL (пусто, если все базы файловые)
  srv: "localhost"                            #имя или IP адрес
  port: 5433

schedule_settings: 
  daily:
    delete_older: 20160                       #Сколькок минут хранить ежедневные копии
  weekly:
    delete_older: 90                          #Сколькок дней хранить еженедельные копии
  monthly:
    delete_older: 365                         #Сколькок дней хранить ежемесячные копии
    maintenance_types:
      - STATISTICS
      - INDEXES
      - INTEGRITY

bases:
  - mode: "file"
    dbdir: '//172.30.1.11/TestFileDB/'        #При работе из Linux сетевые пути поддерживаются, если установлена cifs-utils. При работе из Windows сетевые пути поддерживаются нативно
    dbname: "filedb01"                        #Для файловых баз нужно только для формирования имени резервной копии
    chkdb: false                              #Выполнять проверку этой БД улилитой chdbfl.exe (только для Windows) или средствами СУБД по настройкам maintenance_types
    validate_restore: false                   #Выполнять проверку резервной копии после выгрузки. Использовать с осторожностью, особенно для больших БД. Требуется значительно больше времени. Программа разворачивает временную пустую базу, восстанввливает данные из резервной копии, проверяет корректность загрузки, затем удаляет временную базу.
    schedules:                                #В каких расписаниях участвует эта БД
      - weekly
      - monthly
  - mode: "file"
    dbdir: '/home/admins/testfiledb/'
    dbname: "filedb02"
    chkdb: false
    validate_restore: false
    schedules:
      - weekly
      - monthly
  - mode: "dbms"
    dbname: "test01"
    chkdb: false
    validate_restore: false
    schedules:
      - daily
      - weekly
      - monthly