general:
  backups_path: "/mnt/storage/"
  ibcmd_path: "/opt/1cv8/x86_64/8.3.24.1548/" #Обязательно после каждого обновления платформы 1С исправлять на новый!
  log_path: "/home/backup/"
  1c_stop: true                               #Останавливать службу сервера 1С. (рекомендуется, но не обязательно)
  time_to_start: "23:00"                      #Время для запуска утилиты. Используется только при работе как служба
  secrets_file: "/home/admins//go-projects/maintenance_1C/secrets.yaml"
  mount_path: "/mnt/"                         #Каталог для временного монтирования сетевых файловых баз при работе из Linux  

server_settings:
  dbms: "PostgreSQL"                          #Может быть только PostgreSQL или MSSQL (пусто, если все базы файловые)
  srv: "localhost"                            #имя или IP адрес
  port: 5433

schedule_settings:                            #Чтобы включить расписание, необходимо добавить нужный блок в эту секцию. Допустимы три вида блоков - daily, weekly, monthly
  daily:
    schedule_backup_dir: "daily"              #Каталог внутри backups_path, в который будут сохраняться ежедневные копии
    schedule_days:                            #Укажите номера дней недели, в которые должно срабатывать расписание, где 1-6 это понедельник-суббота, 0 - воскресенье
    - 1
    - 2
    - 3
    - 4
    - 5
    delete_older: 20160                       #Сколько минут хранить ежедневные копии
    maintenance_types:                        #Виды ежедневного обслуживания. Для PostgreSQL - ANALYZE, REINDEX, VACUUM, VACUUM_FULL. Для MSSQL - STATISTICS (UPDATE STATISTICS), INDEXES (REORGANIZE / REBUILD), INTEGRITY (DBCC CHECKDB)
      - STATISTICS
  weekly:
    schedule_backup_dir: "weekly"             #Каталог внутри backups_path, в который будут сохраняться еженедельные копии
    schedule_days:                            #Укажите номера дней недели, в которые должно срабатывать расписание, где 1-6 это понедельник-суббота, 0 - воскресенье. В указанные здесь дни, при совпадении, не будет выполняться расписание daily
    - 6
    delete_older: 90                          #Сколько дней хранить еженедельные копии
    maintenance_types:
      - STATISTICS
      - INTEGRITY
  monthly:
    schedule_backup_dir: "monthly"            #Каталог внутри backups_path, в который будут сохраняться ежемесячные копии
    schedule_days:                            #Укажите номера дней месяца, в которые должно срабатывать расписание. В указанные здесь дни, при совпадении, не будут выполняться расписания daily и weekly
    - 15
    - 31                                      #Если указанного числа нет в текущем месяце, запуск выполняется в последний день месяца.
    delete_older: 365                         #Сколько дней хранить ежемесячные копии
    maintenance_types:
      - STATISTICS
      - INDEXES
      - INTEGRITY

bases:
  - mode: "file"
    dbdir: '//172.30.1.11/TestFileDB/'        #При работе из Linux сетевые пути поддерживаются, если установлена cifs-utils. При работе из Windows сетевые пути поддерживаются нативно
    dbname: "filedb01"                        #Для файловых баз нужно только для формирования имени резервной копии
    chkdb: false                              #Выполнять проверку этой БД улилитой chdbfl.exe (только для Windows) или средствами СУБД по настройкам maintenance_types
    validate_restore: false                   #Выполнять проверку резервной копии после выгрузки. Использовать с осторожностью, особенно для больших БД. Требуется значительно больше времени. Программа разворачивает временную пустую базу, восстанввливает данные из резервной копии, проверяет корректность загрузки, затем удаляет временную базу.
    schedules:                                #В каких расписаниях участвует эта БД
      - weekly
      - monthly
  - mode: "file"
    dbdir: '/home/admins/testfiledb/'
    dbname: "filedb02"
    chkdb: false
    validate_restore: false
    schedules:
      - weekly
      - monthly
  - mode: "dbms"
    dbname: "test01"
    chkdb: false
    validate_restore: false
    schedules:
      - daily
      - weekly
      - monthly

# Advansed DBMS's settings (optional)
postgres:
  jobs: 2
  vacuum_full:
    enabled: false
    min_bloat: 50
    exclude_tables:
      - ...
  statement_timeout: 0
  lock_timeout: 0
  idle_in_transaction_session_timeout: 3600000

mssql:
  index_maintenance:
    reorganize_from: 10
    rebuild_from: 30
    min_pages: 1000
  checkdb:
    physical_only: false